---
title: "Data import"
output: github_document
Date: 9/20/2022
---


```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

##Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

##Take a look at the data

Printing in the console.

```{r}
litters_df 
```

```{r}
tail(litters_df) 
```

```{r}
skimr::skim(litters_df)
```

##Options to read csv

```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

##Other file formats

Read in an excel file.

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in a sas file

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

##Comparison with Base R



# Data maniputation

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## 'select'

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns

```{r}
select(litters_df, GROUP = group)
```

```{r}
rename(litters_df, GROUP = group)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## 'filter'

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

Whether =20?
```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
filter(litters_df, gd_of_birth != 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

